export const products = [
  // SPICES
  { name: 'Red Chilli Powder',      hindi_name: 'लाल मिर्च',      category: 'Spices',           grade: 'Ground · Custom SHU',    image_url: 'red-chili.jpg',    origin: 'Guntur, Andhra Pradesh' },
  { name: 'Kashmiri Mirchi Powder', hindi_name: 'कश्मीरी मिर्च',  category: 'Spices',           grade: 'Ground · Deep Colour',   image_url: null,               origin: 'Kashmir' },
  { name: 'Dhania Powder',          hindi_name: 'धनिया',           category: 'Spices',           grade: 'Ground · Fine-milled',   image_url: 'coriander.jpg',    origin: 'Rajasthan' },
  { name: 'Haldi Powder',           hindi_name: 'हल्दी',           category: 'Spices',           grade: 'Ground · High-curcumin', image_url: 'turmeric.jpg',     origin: 'Sangli, Maharashtra' },
  { name: 'Goda Masala',            hindi_name: 'गोडा मसाला',      category: 'Spices',           grade: 'Blend · Maharashtra',    image_url: null,               origin: 'Maharashtra' },
  { name: 'Kanda-Lasoon Masala',    hindi_name: 'कांदा-लसूण',      category: 'Spices',           grade: 'Blend · Traditional',    image_url: null,               origin: 'Maharashtra' },
  { name: 'Garam Masala',           hindi_name: 'गरम मसाला',       category: 'Spices',           grade: 'Blend · Aromatic',       image_url: null,               origin: 'India' },
  { name: 'Chaat Masala',           hindi_name: 'चाट मसाला',       category: 'Spices',           grade: 'Blend · Tangy',          image_url: null,               origin: 'India' },
  // POWDERS
  { name: 'Dalchini Powder',        hindi_name: 'दालचीनी',         category: 'Powders',          grade: 'Ground · True quills',   image_url: 'cinnamon.jpg',     origin: 'Kerala' },
  { name: 'Moringa Powder',         hindi_name: 'मोरिंगा',          category: 'Powders',          grade: 'Ground · Superfood',     image_url: null,               origin: 'Tamil Nadu' },
  { name: 'Black Pepper Powder',    hindi_name: 'काली मिर्च',       category: 'Powders',          grade: 'Ground · Malabar',       image_url: 'black-pepper.jpg', origin: 'Kerala' },
  { name: 'Jeera Powder',           hindi_name: 'जीरा',             category: 'Powders',          grade: 'Ground · Sun-dried',     image_url: 'cumin.jpg',        origin: 'Rajasthan' },
  { name: 'Elaichi Powder',         hindi_name: 'इलायची',           category: 'Powders',          grade: 'Ground · Green pods',    image_url: 'cardamom.jpg',     origin: 'Kerala' },
  { name: 'Dry Ginger Powder',      hindi_name: 'सोंठ',             category: 'Powders',          grade: 'Ground · Aromatic',      image_url: null,               origin: 'Kerala' },
  // SEEDS
  { name: 'Mohari',                 hindi_name: 'मोहरी',            category: 'Seeds',            grade: 'Mustard · Whole',        image_url: null,               origin: 'Rajasthan' },
  { name: 'Jeera',                  hindi_name: 'जीरा',             category: 'Seeds',            grade: 'Cumin · Whole',          image_url: 'cumin.jpg',        origin: 'Rajasthan' },
  { name: 'Methi',                  hindi_name: 'मेथी',             category: 'Seeds',            grade: 'Fenugreek · Whole',      image_url: null,               origin: 'Rajasthan' },
  { name: 'Ajwain',                 hindi_name: 'अजवाइन',           category: 'Seeds',            grade: 'Carom · Whole',          image_url: null,               origin: 'Rajasthan' },
  { name: 'Saunf',                  hindi_name: 'सौंफ',              category: 'Seeds',            grade: 'Fennel · Whole',         image_url: null,               origin: 'Gujarat' },
  { name: 'Sunflower Seeds',        hindi_name: null,               category: 'Seeds',            grade: 'Raw · Hulled',           image_url: null,               origin: 'Maharashtra' },
  { name: 'Pumpkin Seeds',          hindi_name: null,               category: 'Seeds',            grade: 'Raw · Hulled',           image_url: null,               origin: 'India' },
  { name: 'Chia Seeds',             hindi_name: null,               category: 'Seeds',            grade: 'Superfood',              image_url: null,               origin: 'India' },
  { name: 'Flax Seeds',             hindi_name: 'अलसी',             category: 'Seeds',            grade: 'Omega-3 Rich',           image_url: null,               origin: 'Madhya Pradesh' },
  { name: 'Sesame Seeds',           hindi_name: 'तिल',              category: 'Seeds',            grade: 'Whole · White',          image_url: null,               origin: 'Gujarat' },
  { name: 'Mix Seeds',              hindi_name: null,               category: 'Seeds',            grade: 'Blend · 6-seed',         image_url: null,               origin: 'India' },
  // MILLETS & GRAINS
  { name: 'Jowar',                  hindi_name: 'ज्वार',            category: 'Millets & Grains', grade: 'Sorghum · Whole',        image_url: null,               origin: 'Maharashtra' },
  { name: 'Rajgira',                hindi_name: 'राजगिरा',          category: 'Millets & Grains', grade: 'Amaranth · Whole',       image_url: null,               origin: 'Maharashtra' },
  { name: 'Bajra',                  hindi_name: 'बाजरा',            category: 'Millets & Grains', grade: 'Pearl Millet · Whole',   image_url: null,               origin: 'Rajasthan' },
  { name: 'Ragi',                   hindi_name: 'रागी',             category: 'Millets & Grains', grade: 'Finger Millet · Whole',  image_url: null,               origin: 'Karnataka' },
  { name: 'Quinoa',                 hindi_name: 'क्विनोआ',          category: 'Millets & Grains', grade: 'Superfood · White',      image_url: null,               origin: 'India' },
  { name: 'Rolled Oats',            hindi_name: null,               category: 'Millets & Grains', grade: 'Quick Cook',             image_url: null,               origin: 'India' },
  { name: 'Oats',                   hindi_name: null,               category: 'Millets & Grains', grade: 'Whole Grain',            image_url: null,               origin: 'India' },
  { name: 'Bhagar',                 hindi_name: 'भगर',              category: 'Millets & Grains', grade: 'Barnyard Millet',        image_url: null,               origin: 'Maharashtra' },
  { name: 'Makhana Plain',          hindi_name: 'मखाना',            category: 'Millets & Grains', grade: 'Fox Nuts · Plain',       image_url: null,               origin: 'Bihar' },
  { name: 'Makhana Flavoured',      hindi_name: 'मखाना',            category: 'Millets & Grains', grade: 'Fox Nuts · Seasoned',    image_url: null,               origin: 'Bihar' },
  // SALT & MINERALS
  { name: 'Black Salt',             hindi_name: 'काला नमक',         category: 'Salt & Minerals',  grade: 'Kala Namak · Fine',      image_url: null,               origin: 'Himalayan' },
  { name: 'Rock Salt',              hindi_name: 'सेंधा नमक',        category: 'Salt & Minerals',  grade: 'Himalayan · Coarse',     image_url: null,               origin: 'Himalayan' },
  { name: 'Pink Salt',              hindi_name: 'गुलाबी नमक',       category: 'Salt & Minerals',  grade: 'Himalayan · Fine',       image_url: null,               origin: 'Himalayan' },
  // SEASONINGS
  { name: 'Peri Peri Powder',       hindi_name: null,               category: 'Seasonings',       grade: 'Blend · Spicy',          image_url: null,               origin: 'India' },
  { name: 'Garlic Powder',          hindi_name: 'लहसुन',            category: 'Seasonings',       grade: 'Ground · Dehydrated',    image_url: null,               origin: 'Madhya Pradesh' },
  { name: 'Onion Powder',           hindi_name: 'प्याज',             category: 'Seasonings',       grade: 'Ground · Dehydrated',    image_url: null,               origin: 'Maharashtra' },
  { name: 'Tomato Powder',          hindi_name: 'टमाटर',            category: 'Seasonings',       grade: 'Ground · Dehydrated',    image_url: null,               origin: 'India' },
  { name: 'Oregano',                hindi_name: null,               category: 'Seasonings',       grade: 'Dried · Mediterranean',  image_url: null,               origin: 'India' },
  { name: 'Chilli Flakes',          hindi_name: null,               category: 'Seasonings',       grade: 'Crushed · Medium heat',  image_url: null,               origin: 'Andhra Pradesh' },
  { name: 'Pizza Pasta Seasoning',  hindi_name: null,               category: 'Seasonings',       grade: 'Blend',                  image_url: null,               origin: 'India' },
  { name: 'Nutmeg Powder',          hindi_name: 'जायफल',            category: 'Seasonings',       grade: 'Ground · Whole',         image_url: null,               origin: 'Kerala' },
];
